# Generated by Django 4.0.3 on 2022-03-12 17:39

from django.db import migrations, models
import plant.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrdeictPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_pic', models.ImageField(default='media\\channel.png', upload_to=plant.models.upload_to)),
            ],
        ),
    ]
