# Generated by Django 4.0.3 on 2022-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_prdeictplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdeictplant',
            name='plant_pic',
            field=models.ImageField(default='media\\channel.png', upload_to='plants'),
        ),
    ]
